export const dynamicExitQueueAbi = [
    {
        type: 'function',
        name: 'escrow',
        inputs: [],
        outputs: [{ name: '', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'feePercent',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'minFeePercent',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'cooldown',
        inputs: [],
        outputs: [{ name: '', type: 'uint48' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'minCooldown',
        inputs: [],
        outputs: [{ name: '', type: 'uint48' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'calculateFee',
        inputs: [{ name: '_tokenId', type: 'uint256' }],
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'canExit',
        inputs: [{ name: '_tokenId', type: 'uint256' }],
        outputs: [{ name: '', type: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'isCool',
        inputs: [{ name: '_tokenId', type: 'uint256' }],
        outputs: [{ name: '', type: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'queue',
        inputs: [{ name: '_tokenId', type: 'uint256' }],
        outputs: [
            {
                name: '',
                type: 'tuple',
                components: [
                    { name: 'holder', type: 'address' },
                    { name: 'queuedAt', type: 'uint48' },
                    { name: 'minCooldown', type: 'uint48' },
                    { name: 'cooldown', type: 'uint48' },
                    { name: 'feePercent', type: 'uint16' },
                    { name: 'minFeePercent', type: 'uint16' },
                    { name: 'slope', type: 'uint256' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'exit',
        inputs: [{ name: '_tokenId', type: 'uint256' }],
        outputs: [{ name: 'fee', type: 'uint256' }],
        stateMutability: 'nonpayable',
    },
] as const;
