// Auto-generated by: just export-abi
// Do not edit manually.

export const memberRegistryAbi = [
    {
        type: 'constructor',
        inputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'REVOKE_MEMBER_PERMISSION_ID',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'bytes32',
                internalType: 'bytes32',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'UPGRADE_REGISTRY_PERMISSION_ID',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'bytes32',
                internalType: 'bytes32',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'dao',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'address',
                internalType: 'contract IDAO',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'ens',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'address',
                internalType: 'contract ENS',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'initialize',
        inputs: [
            {
                name: '_managementDao',
                type: 'address',
                internalType: 'contract IDAO',
            },
            {
                name: '_ens',
                type: 'address',
                internalType: 'contract ENS',
            },
            {
                name: '_node',
                type: 'bytes32',
                internalType: 'bytes32',
            },
            {
                name: '_resolver',
                type: 'address',
                internalType: 'address',
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'isRegistered',
        inputs: [
            {
                name: 'member',
                type: 'address',
                internalType: 'address',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'bool',
                internalType: 'bool',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'labelOwner',
        inputs: [
            {
                name: '',
                type: 'bytes32',
                internalType: 'bytes32',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'address',
                internalType: 'address',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'memberLabel',
        inputs: [
            {
                name: '',
                type: 'address',
                internalType: 'address',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'bytes32',
                internalType: 'bytes32',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'memberSubdomain',
        inputs: [
            {
                name: '',
                type: 'address',
                internalType: 'address',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'string',
                internalType: 'string',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'node',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'bytes32',
                internalType: 'bytes32',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'protocolVersion',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'uint8[3]',
                internalType: 'uint8[3]',
            },
        ],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'proxiableUUID',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'bytes32',
                internalType: 'bytes32',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'register',
        inputs: [
            {
                name: 'subdomain',
                type: 'string',
                internalType: 'string',
            },
            {
                name: 'records',
                type: 'tuple',
                internalType: 'struct IMemberRegistry.Records',
                components: [
                    {
                        name: 'textRecords',
                        type: 'tuple[]',
                        internalType: 'struct IMemberRegistry.TextRecord[]',
                        components: [
                            {
                                name: 'key',
                                type: 'string',
                                internalType: 'string',
                            },
                            {
                                name: 'value',
                                type: 'string',
                                internalType: 'string',
                            },
                        ],
                    },
                    {
                        name: 'addr',
                        type: 'address',
                        internalType: 'address',
                    },
                    {
                        name: 'contenthash',
                        type: 'bytes',
                        internalType: 'bytes',
                    },
                ],
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'register',
        inputs: [
            {
                name: 'subdomain',
                type: 'string',
                internalType: 'string',
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'release',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'rename',
        inputs: [
            {
                name: 'newSubdomain',
                type: 'string',
                internalType: 'string',
            },
            {
                name: 'records',
                type: 'tuple',
                internalType: 'struct IMemberRegistry.Records',
                components: [
                    {
                        name: 'textRecords',
                        type: 'tuple[]',
                        internalType: 'struct IMemberRegistry.TextRecord[]',
                        components: [
                            {
                                name: 'key',
                                type: 'string',
                                internalType: 'string',
                            },
                            {
                                name: 'value',
                                type: 'string',
                                internalType: 'string',
                            },
                        ],
                    },
                    {
                        name: 'addr',
                        type: 'address',
                        internalType: 'address',
                    },
                    {
                        name: 'contenthash',
                        type: 'bytes',
                        internalType: 'bytes',
                    },
                ],
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'rename',
        inputs: [
            {
                name: 'newSubdomain',
                type: 'string',
                internalType: 'string',
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'resolver',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'address',
                internalType: 'address',
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'revoke',
        inputs: [
            {
                name: 'member',
                type: 'address',
                internalType: 'address',
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'upgradeTo',
        inputs: [
            {
                name: 'newImplementation',
                type: 'address',
                internalType: 'address',
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'upgradeToAndCall',
        inputs: [
            {
                name: 'newImplementation',
                type: 'address',
                internalType: 'address',
            },
            {
                name: 'data',
                type: 'bytes',
                internalType: 'bytes',
            },
        ],
        outputs: [],
        stateMutability: 'payable',
    },
    {
        type: 'event',
        name: 'AdminChanged',
        inputs: [
            {
                name: 'previousAdmin',
                type: 'address',
                indexed: false,
                internalType: 'address',
            },
            {
                name: 'newAdmin',
                type: 'address',
                indexed: false,
                internalType: 'address',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'BeaconUpgraded',
        inputs: [
            {
                name: 'beacon',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Initialized',
        inputs: [
            {
                name: 'version',
                type: 'uint8',
                indexed: false,
                internalType: 'uint8',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'MemberRegistered',
        inputs: [
            {
                name: 'member',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'subdomain',
                type: 'string',
                indexed: false,
                internalType: 'string',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'MemberReleased',
        inputs: [
            {
                name: 'member',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'subdomain',
                type: 'string',
                indexed: false,
                internalType: 'string',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'MemberRenamed',
        inputs: [
            {
                name: 'member',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'oldSubdomain',
                type: 'string',
                indexed: false,
                internalType: 'string',
            },
            {
                name: 'newSubdomain',
                type: 'string',
                indexed: false,
                internalType: 'string',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'MemberRevoked',
        inputs: [
            {
                name: 'member',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'revoker',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'subdomain',
                type: 'string',
                indexed: false,
                internalType: 'string',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Upgraded',
        inputs: [
            {
                name: 'implementation',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
        ],
        anonymous: false,
    },
    {
        type: 'error',
        name: 'AlreadyRegistered',
        inputs: [
            {
                name: 'member',
                type: 'address',
                internalType: 'address',
            },
        ],
    },
    {
        type: 'error',
        name: 'DaoUnauthorized',
        inputs: [
            {
                name: 'dao',
                type: 'address',
                internalType: 'address',
            },
            {
                name: 'where',
                type: 'address',
                internalType: 'address',
            },
            {
                name: 'who',
                type: 'address',
                internalType: 'address',
            },
            {
                name: 'permissionId',
                type: 'bytes32',
                internalType: 'bytes32',
            },
        ],
    },
    {
        type: 'error',
        name: 'InvalidENSRegistry',
        inputs: [
            {
                name: 'ens',
                type: 'address',
                internalType: 'address',
            },
        ],
    },
    {
        type: 'error',
        name: 'InvalidNode',
        inputs: [],
    },
    {
        type: 'error',
        name: 'InvalidSubdomain',
        inputs: [
            {
                name: 'subdomain',
                type: 'string',
                internalType: 'string',
            },
        ],
    },
    {
        type: 'error',
        name: 'NotRegistered',
        inputs: [
            {
                name: 'member',
                type: 'address',
                internalType: 'address',
            },
        ],
    },
    {
        type: 'error',
        name: 'SubdomainAlreadyTaken',
        inputs: [
            {
                name: 'subdomain',
                type: 'string',
                internalType: 'string',
            },
        ],
    },
] as const;
