// Auto-generated by: just export-abi
// Do not edit manually.

export const memberRegistryAbi = [
    { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        name: 'EVICT_SUBDOMAIN_PERMISSION_ID',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'UPGRADE_REGISTRY_PERMISSION_ID',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'dao',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'contract IDAO' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'ens',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'contract ENS' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'evict',
        inputs: [
            { name: 'subdomain', type: 'string', internalType: 'string' },
            { name: 'newController', type: 'address', internalType: 'address' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'initialize',
        inputs: [
            {
                name: '_managementDao',
                type: 'address',
                internalType: 'contract IDAO',
            },
            { name: '_ens', type: 'address', internalType: 'contract ENS' },
            { name: '_domain', type: 'string', internalType: 'string' },
            { name: '_resolver', type: 'address', internalType: 'address' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'isRegistered',
        inputs: [{ name: 'member', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'labelOwner',
        inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'memberLabel',
        inputs: [{ name: '', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'memberSubdomain',
        inputs: [{ name: '', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'string', internalType: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'move',
        inputs: [
            { name: 'newSubdomain', type: 'string', internalType: 'string' },
            {
                name: 'records',
                type: 'tuple',
                internalType: 'struct IMemberRegistry.Records',
                components: [
                    {
                        name: 'textRecords',
                        type: 'tuple[]',
                        internalType: 'struct IMemberRegistry.TextRecord[]',
                        components: [
                            {
                                name: 'key',
                                type: 'string',
                                internalType: 'string',
                            },
                            {
                                name: 'value',
                                type: 'string',
                                internalType: 'string',
                            },
                        ],
                    },
                    { name: 'addr', type: 'address', internalType: 'address' },
                    {
                        name: 'contenthash',
                        type: 'bytes',
                        internalType: 'bytes',
                    },
                ],
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'move',
        inputs: [
            { name: 'newSubdomain', type: 'string', internalType: 'string' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'parentDomain',
        inputs: [],
        outputs: [{ name: '', type: 'string', internalType: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'parentNode',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'register',
        inputs: [
            { name: 'subdomain', type: 'string', internalType: 'string' },
            {
                name: 'records',
                type: 'tuple',
                internalType: 'struct IMemberRegistry.Records',
                components: [
                    {
                        name: 'textRecords',
                        type: 'tuple[]',
                        internalType: 'struct IMemberRegistry.TextRecord[]',
                        components: [
                            {
                                name: 'key',
                                type: 'string',
                                internalType: 'string',
                            },
                            {
                                name: 'value',
                                type: 'string',
                                internalType: 'string',
                            },
                        ],
                    },
                    { name: 'addr', type: 'address', internalType: 'address' },
                    {
                        name: 'contenthash',
                        type: 'bytes',
                        internalType: 'bytes',
                    },
                ],
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'register',
        inputs: [{ name: 'subdomain', type: 'string', internalType: 'string' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'release',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'resolver',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
] as const;
