name: Changeset Version
description: Runs `pnpm changeset version` and formats CHANGELOG.md (idempotent when no changesets).

inputs:
  prettier_changelog:
    description: Whether to format CHANGELOG.md with prettier
    required: false
    default: "true"
  github_token:
    description: GitHub token for changesets (optional but recommended)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail
        pnpm changeset version
        if [ "${{ inputs.prettier_changelog }}" = "true" ]; then
          pnpm dlx prettier --write --prose-wrap never CHANGELOG.md
        fi

