name: Generate Release Summary
description: Generates a PR/Slack-friendly release summary based on git log range (optionally from a base tag).

inputs:
  linear_api_token:
    description: Linear API token for fetching issue titles (optional)
    required: false
    default: ""
  base_ref:
    description: |
      Override base ref for summary range (optional, not recommended).
      Auto-detection finds the latest semver tag and computes merge-base,
      which works correctly for both releases and hotfixes.
      Only use this for debugging or edge cases.
    required: false
    default: ""

outputs:
  summary:
    description: Generated summary markdown
    value: ${{ steps.summary.outputs.summary }}

runs:
  using: composite
  steps:
    - id: summary
      shell: bash
      env:
        LINEAR_API_TOKEN: ${{ inputs.linear_api_token }}
        BASE_REF: ${{ inputs.base_ref }}
      run: |
        set -euo pipefail
        node .github/workflows/scripts/generateReleaseSummary.js

