export enum CapitalFlowDialogId {
    CREATE_POLICY_DETAILS = 'CREATE_POLICY_DETAILS',
    SETUP_STRATEGY = 'SETUP_STRATEGY',
    PREPARE_POLICY = 'PREPARE_POLICY',
    ROUTER_SELECTOR = 'ROUTER_SELECTOR',
    DISPATCH = 'DISPATCH',
    DISPATCH_TRANSACTION = 'DISPATCH_TRANSACTION',
}
