export enum CapitalFlowDaoSlotId {
    CAPITAL_DISTRIBUTOR_MEMBERS_FILE_DOWNLOAD = 'CAPITAL_DISTRIBUTOR_MEMBERS_FILE_DOWNLOAD',
    CAPITAL_DISTRIBUTOR_VOTING_ESCROW_ADDRESS = 'CAPITAL_DISTRIBUTOR_VOTING_ESCROW_ADDRESS',
}
