export enum ProposalActionType {
    WITHDRAW_TOKEN = 'WITHDRAW_TOKEN',
    ADD_MEMBERS = 'ADD_MEMBERS',
    REMOVE_MEMBERS = 'REMOVE_MEMBERS',
    UPDATE_METADATA = 'UPDATE_METADATA',
    TOKEN_MINT = 'TOKEN_MINT',
    CHANGE_SETTINGS_MULTISIG = 'CHANGE_SETTINGS_MULTISIG',
    CHANGE_SETTINGS_TOKENVOTE = 'CHANGE_SETTINGS_TOKENVOTE',
}
