name: Read Changelog Section
description: Extracts the changelog section for a given version from CHANGELOG.md (outputs 'changes').

inputs:
  version:
    description: Version to read (e.g. 1.2.3)
    required: true
  path:
    description: Path to changelog file
    required: false
    default: ./CHANGELOG.md

outputs:
  changes:
    description: Extracted changelog text for that version
    value: ${{ steps.read.outputs.changes }}

runs:
  using: composite
  steps:
    - id: read
      uses: actions/github-script@v8.0.0
      env:
        version: ${{ inputs.version }}
        path: ${{ inputs.path }}
      with:
        script: |
          const readChangelog = require('./.github/workflows/scripts/readChangelog.js');
          await readChangelog({ github, context, core });

