name: Ensure Pull Request
description: Ensures a PR exists for a head branch into a base branch.

inputs:
  base:
    description: Base branch
    required: true
  head:
    description: Head branch
    required: true
  title:
    description: PR title
    required: true
  body:
    description: PR body
    required: true
  token:
    description: GitHub token (PAT recommended)
    required: true

outputs:
  url:
    description: PR url
    value: ${{ steps.ensure.outputs.url }}
  number:
    description: PR number
    value: ${{ steps.ensure.outputs.number }}

runs:
  using: composite
  steps:
    - id: ensure
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        BODY: ${{ inputs.body }}
      run: |
        set -euo pipefail
        HEAD="${{ inputs.head }}"
        BASE="${{ inputs.base }}"

        URL="$(gh pr list --head "$HEAD" --state open --json url -q '.[0].url' || true)"
        NUMBER="$(gh pr list --head "$HEAD" --state open --json number -q '.[0].number' || true)"

        if [ -n "$URL" ] && [ "$URL" != "null" ]; then
          echo "url=$URL" >> "$GITHUB_OUTPUT"
          echo "number=$NUMBER" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        BODY_FILE="$(mktemp)"
        printf "%s" "$BODY" > "$BODY_FILE"

        URL="$(gh pr create --base "$BASE" --head "$HEAD" --title "${{ inputs.title }}" --body-file "$BODY_FILE")"
        NUMBER="$(gh pr view "$URL" --json number -q .number)"
        echo "url=$URL" >> "$GITHUB_OUTPUT"
        echo "number=$NUMBER" >> "$GITHUB_OUTPUT"

