export enum ApplicationDialogId {
    CONNECT_WALLET = 'CONNECT_WALLET',
    USER = 'USER',
    ARAGON_PROFILE_INTRO = 'ARAGON_PROFILE_INTRO',
    ARAGON_PROFILE_CLAIM_SUBDOMAIN = 'ARAGON_PROFILE_CLAIM_SUBDOMAIN',
    ARAGON_PROFILE_CLAIM_SUBDOMAIN_TX = 'ARAGON_PROFILE_CLAIM_SUBDOMAIN_TX',
    ARAGON_PROFILE_SET_REVERSE_ENS_TX = 'ARAGON_PROFILE_SET_REVERSE_ENS_TX',
    ARAGON_PROFILE = 'ARAGON_PROFILE',
    ARAGON_PROFILE_UPDATE = 'ARAGON_PROFILE_UPDATE',
}
