minimumReleaseAge: 10080 # cooldown period for new packages in minutes (7 days)
minimumReleaseAgeExclude:
  # https://pnpm.io/settings#minimumreleaseageexclude
strictDepBuilds: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 131400 # skip trust checks for packages published >3 months ago
overrides:
  jsdom: 26.1.0
  esbuild@<0.28.1: '>=0.28.1'
  js-yaml@>=4.0.0 <4.1.2: '>=4.2.0'
  undici@<6.24.0: '>=6.24.0'
  serialize-javascript@<7.0.3: ^7.0.3
  tar@<7.5.11: ^7.5.11
  ajv@<8.18.0: ^8.18.0
  minimatch@>=10.0.0 <10.2.4: ^10.2.4
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  path-to-regexp@>=8.0.0 <8.4.0: '>=8.4.0'
  smol-toml@<1.6.1: '>=1.6.1'
  srvx@<0.11.13: '>=0.11.13'
  ws@>=8.0.0 <8.21.0: '>=8.21.0'
  '@vercel/fun>@tootallnate/once': ^3.0.1
  '@hookform/devtools>uuid': ^14.0.0
packageExtensions:
  '@solana/codecs-strings@*':
    dependencies:
      fastestsmallesttextencoderdecoder: ^1.0.22
savePrefix: ^
strictPeerDependencies: true
autoInstallPeers: false
sideEffectsCache: true
preferFrozenLockfile: true
dedupePeerDependents: true
ignoreScripts: true
autoInstallTypes: true
nodeVersion: 24.16.0
engineStrict: true
