minimumReleaseAge: 10080 # cooldown period for new packages in minutes (7 days)
minimumReleaseAgeExclude: # https://pnpm.io/settings#minimumreleaseageexclude
  - rolldown@1.0.0-rc.15
  - "@rolldown/pluginutils"
  - "@rolldown/binding-darwin-arm64"
  - "@rolldown/binding-darwin-x64"
  - "@rolldown/binding-win32-x64-msvc"
  - "@rolldown/binding-linux-x64-gnu"
  - "@rolldown/binding-linux-x64-musl"
  - "@rolldown/binding-freebsd-x64"
  - "@rolldown/binding-linux-arm-gnueabihf"
  - "@rolldown/binding-linux-arm64-gnu"
  - "@rolldown/binding-linux-arm64-musl"
  - "@rolldown/binding-openharmony-arm64"
  - "@rolldown/binding-win32-arm64-msvc"
  - "@rolldown/binding-android-arm64"
  - "@rolldown/binding-wasm32-wasi"
  - "@rolldown/binding-linux-s390x-gnu"
  - "@rolldown/binding-linux-ppc64-gnu"
strictDepBuilds: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 131400 # skip trust checks for packages published >3 months ago
