import type { IProposalAction } from '../../api/governanceService';
import type { IProposalCreate } from '../../dialogs/publishProposalDialog';

export type IProposalActionData<TAction extends IProposalAction = IProposalAction, TMeta = undefined> = TAction & {
    /**
     * ID of the action generated by the form handler.
     */
    id?: string;
    /**
     * ID of the DAO.
     */
    daoId: string;
    /**
     * Additional metadata for the action.
     */
    meta: TMeta;
};

export interface ICreateProposalFormData<TMeta = undefined> extends Omit<IProposalCreate, 'actions'> {
    /**
     * Defines if the user wants to add actions to the proposal or not.
     */
    addActions: boolean;
    /**
     * List of actions to be executed if the proposal succeeds.
     */
    actions: Array<IProposalActionData<IProposalAction, TMeta>>;
}
