import type { IProposalAction } from '../../api/governanceService';
import type { IProposalCreate } from '../../dialogs/publishProposalDialog';

export type IProposalActionData<
    TAction extends IProposalAction = IProposalAction,
    TMeta = undefined,
> = TAction & {
    /**
     * ID of the action generated by the form handler.
     */
    id?: string;
    /**
     * Stable client-side id used as the React key of the rendered action item. Owned by the form
     * (not react-hook-form), so it survives the field array id being regenerated when the action
     * decoder re-encodes calldata on every keystroke. Whitelisted out of submit and export payloads.
     */
    fieldId?: string;
    /**
     * ID of the DAO.
     */
    daoId: string;
    /**
     * Additional metadata for the action.
     */
    meta: TMeta;
};

export interface ICreateProposalFormData<TMeta = undefined>
    extends Omit<IProposalCreate, 'actions'> {
    /**
     * Defines if the user wants to add actions to the proposal or not.
     */
    addActions: boolean;
    /**
     * List of actions to be executed if the proposal succeeds.
     */
    actions: IProposalActionData<IProposalAction, TMeta>[];
}
