export enum GovernanceDialogId {
    PUBLISH_PROPOSAL = 'PUBLISH_PROPOSAL',
    VOTE = 'VOTE',
    EXECUTE = 'EXECUTE',
    SELECT_PLUGIN = 'SELECT_PLUGIN',
    VERIFY_SMART_CONTRACT = 'VERIFY_SMART_CONTRACT',
    PERMISSION_CHECK = 'PERMISSION_CHECK',
    WALLET_CONNECT_ACTION = 'WALLET_CONNECT_ACTION',
}
