export enum GovernanceSlotId {
    GOVERNANCE_DAO_MEMBER_LIST = 'GOVERNANCE_DAO_MEMBER_LIST',
    GOVERNANCE_DAO_PROPOSAL_LIST = 'GOVERNANCE_DAO_PROPOSAL_LIST',
    GOVERNANCE_MEMBER_STATS = 'GOVERNANCE_MEMBER_STATS',
    GOVERNANCE_PROPOSAL_VOTING_BREAKDOWN = 'GOVERNANCE_PROPOSAL_VOTING_BREAKDOWN',
    GOVERNANCE_VOTE_LIST = 'GOVERNANCE_VOTE_LIST',
    GOVERNANCE_PROCESS_PROPOSAL_STATUS = 'GOVERNANCE_PROCESS_PROPOSAL_STATUS',
}
