export enum GovernanceSlotId {
    GOVERNANCE_DAO_MEMBER_LIST = 'GOVERNANCE_DAO_MEMBER_LIST',
    GOVERNANCE_DAO_PROPOSAL_LIST = 'GOVERNANCE_DAO_PROPOSAL_LIST',
    GOVERNANCE_MEMBER_STATS = 'GOVERNANCE_MEMBER_STATS',
    GOVERNANCE_PROPOSAL_VOTING_BREAKDOWN = 'GOVERNANCE_PROPOSAL_VOTING_BREAKDOWN',
    GOVERNANCE_VOTE_LIST = 'GOVERNANCE_VOTE_LIST',
    GOVERNANCE_PROCESS_PROPOSAL_STATUS = 'GOVERNANCE_PROCESS_PROPOSAL_STATUS',
    GOVERNANCE_CREATE_PROPOSAL_SETTINGS_FORM = 'GOVERNANCE_CREATE_PROPOSAL_SETTINGS_FORM',
    GOVERNANCE_BUILD_CREATE_PROPOSAL_DATA = 'GOVERNANCE_BUILD_CREATE_PROPOSAL_DATA',
    GOVERNANCE_SUBMIT_VOTE = 'GOVERNANCE_SUBMIT_VOTE',
    GOVERNANCE_BUILD_VOTE_DATA = 'GOVERNANCE_BUILD_VOTE_DATA',
    GOVERNANCE_PROPOSAL_VOTING_TERMINAL = 'GOVERNANCE_PROPOSAL_VOTING_TERMINAL',
    GOVERNANCE_CAN_CREATE_PROPOSAL = 'GOVERNANCE_CAN_CREATE_PROPOSAL',
}
