export enum GovernanceSlotId {
    GOVERNANCE_DAO_MEMBER_LIST = 'GOVERNANCE_DAO_MEMBER_LIST',
    GOVERNANCE_MEMBERS_PAGE_DETAILS = 'GOVERNANCE_MEMBERS_PAGE_DETAILS',
    GOVERNANCE_DAO_PROPOSAL_LIST = 'GOVERNANCE_DAO_PROPOSAL_LIST',
    GOVERNANCE_PROPOSALS_PAGE_DETAILS = 'GOVERNANCE_PROPOSALS_PAGE_DETAILS',
    GOVERNANCE_MEMBER_STATS = 'GOVERNANCE_MEMBER_STATS',
    GOVERNANCE_PROPOSAL_VOTING_BREAKDOWN = 'GOVERNANCE_PROPOSAL_VOTING_BREAKDOWN',
}
