export enum GaugeVoterPluginDialogId {
    GAUGE_DETAILS = 'GAUGE_DETAILS',
    VOTE_GAUGES = 'VOTE_GAUGES', // with _GAUGES suffix to avoid conflict with GovernanceDialogId.VOTE
    VOTE_GAUGES_TRANSACTION = 'VOTE_GAUGES_TRANSACTION',
    LOCK_UNLOCK = 'LOCK_UNLOCK',
    VIEW_LOCKS = 'VIEW_LOCKS',
    EXIT_QUEUE_WITHDRAW_FEE = 'EXIT_QUEUE_WITHDRAW_FEE',
    EXIT_QUEUE_WITHDRAW_TRANSACTION = 'EXIT_QUEUE_WITHDRAW_TRANSACTION',
}
