export const generateRequest = (request?: Partial<Request>): Request & { bytes: unknown } => ({
    cache: 'default',
    credentials: 'omit',
    destination: '',
    headers: {} as Headers,
    integrity: '',
    method: '',
    mode: 'cors',
    redirect: 'error',
    referrer: '',
    referrerPolicy: '',
    url: '',
    keepalive: false,
    signal: {} as AbortSignal,
    clone: jest.fn(),
    body: null,
    bodyUsed: false,
    arrayBuffer: jest.fn(),
    blob: jest.fn(),
    formData: jest.fn(),
    json: jest.fn(),
    text: jest.fn(),
    // TODO tsc command is failing without the "bytes" attribute after update to typescript@5.7.2
    bytes: jest.fn(),
    ...request,
});
