export const generateResponse = (response?: Partial<Response>): Response => ({
    headers: {
        append: jest.fn(),
        delete: jest.fn(),
        get: jest.fn(),
        has: jest.fn(),
        set: jest.fn(),
        getSetCookie: jest.fn(),
        entries: jest.fn(),
        keys: jest.fn(),
        values: jest.fn(),
        forEach: jest.fn(),
        [Symbol.iterator]: jest.fn(),
    },
    ok: true,
    redirected: false,
    status: 200,
    statusText: 'OK',
    type: 'default',
    url: '',
    clone: jest.fn(),
    body: null,
    bodyUsed: false,
    arrayBuffer: jest.fn(),
    blob: jest.fn(),
    formData: jest.fn(),
    text: jest.fn(),
    json: jest.fn(),
    // @ts-expect-error TODO tsc command is failing without the "bytes" attribute after update to typescript@5.7.2
    bytes: jest.fn(),
    ...response,
});
