import 'server-only';
import {
    existsSync,
    mkdirSync,
    readFileSync,
    renameSync,
    writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import type {
    IMpcActivity,
    IMpcSignRequest,
    IMpcSystem,
    IMpcWorkspace,
    IMpcWorkspacePolicy,
} from '@/modules/mpc/api/mpcService/domain';
import type { IMpcEncryptedValue } from './serverCrypto';

/**
 * POC persistence: a single JSON file (default apps/app/.mpc-poc/store.json) loaded once per process and cached
 * on globalThis so it survives Next.js HMR. Writes are atomic (tmp file + rename). Not meant for production.
 */

export interface IMpcStoreUserTotp {
    /**
     * Active TOTP secret (base32, encrypted at rest). Present once the enrollment was confirmed.
     */
    secret?: IMpcEncryptedValue;
    /**
     * Secret generated by the setup endpoint, waiting for the confirmation code. Replaced on every setup call.
     */
    pendingSecret?: IMpcEncryptedValue;
    /**
     * Timestamp of the enrollment confirmation (ISO 8601).
     */
    confirmedAt?: string;
    /**
     * Last TOTP step (30s counter) accepted for this user: a code can only be used once (replay guard).
     */
    lastUsedStep?: number;
}

export interface IMpcStoreUser {
    id: string;
    username: string;
    passwordHash: string;
    salt: string;
    createdAt: string;
    /**
     * TOTP second factor (Google Authenticator style), required on share release / approvals once enrolled.
     */
    totp?: IMpcStoreUserTotp;
}

export interface IMpcStoreSession {
    /**
     * SHA-256 of the session token stored in the cookie.
     */
    id: string;
    userId: string;
    createdAt: string;
    expiresAt: string;
    lastSeenAt: string;
    ip?: string;
    userAgent?: string;
}

export interface IMpcStoreServerShare extends IMpcEncryptedValue {
    /**
     * Epoch of the share, must match the system epoch.
     */
    epoch: number;
}

export interface IMpcStoreSystem extends IMpcSystem {
    /**
     * Server share encrypted at rest (AES-256-GCM). Never returned by the API except through the server-share endpoint.
     */
    serverShare?: IMpcStoreServerShare;
    /**
     * Soft delete timestamp.
     */
    deletedAt?: string;
}

export interface IMpcStoreLoginAttempt {
    failures: number;
    firstFailureAt: number;
    lockedUntil?: number;
}

export interface IMpcStoreData {
    version: 1;
    users: IMpcStoreUser[];
    sessions: IMpcStoreSession[];
    workspaces: IMpcWorkspace[];
    workspacePolicies: IMpcWorkspacePolicy[];
    systems: IMpcStoreSystem[];
    signRequests: IMpcSignRequest[];
    activity: IMpcActivity[];
    loginAttempts: Record<string, IMpcStoreLoginAttempt>;
}

const emptyStoreData = (): IMpcStoreData => ({
    version: 1,
    users: [],
    sessions: [],
    workspaces: [],
    workspacePolicies: [],
    systems: [],
    signRequests: [],
    activity: [],
    loginAttempts: {},
});

export const MPC_DEFAULT_WORKSPACE_NAME = 'Default workspace';

/**
 * Returns the legacy default workspace of a user, creating it in the given store data when missing (the caller
 * persists). Only used by the migration of systems that predate workspaces: new accounts create their
 * workspaces explicitly.
 */
export const ensureDefaultWorkspace = (
    data: IMpcStoreData,
    user: { id: string; username?: string },
): IMpcWorkspace => {
    const existing = data.workspaces.find(
        (item) => item.ownerId === user.id && item.isDefault,
    );

    if (existing != null) {
        return existing;
    }

    const now = nowIso();
    const username =
        user.username ??
        data.users.find((item) => item.id === user.id)?.username ??
        user.id;
    const workspace: IMpcWorkspace = {
        // Deterministic id: migrations stay idempotent across processes.
        id: `ws_${user.id}`,
        name: MPC_DEFAULT_WORKSPACE_NAME,
        ownerId: user.id,
        isDefault: true,
        members: [{ userId: user.id, username, role: 'owner', addedAt: now }],
        createdAt: now,
        updatedAt: now,
    };
    data.workspaces.push(workspace);

    return workspace;
};

/**
 * Brings data persisted by older POC versions up to date: workspaces get their members list (owner included)
 * and systems created before workspaces existed join their creator's legacy default workspace.
 */
export const migrateStoreData = (data: IMpcStoreData): boolean => {
    let changed = false;

    for (const workspace of data.workspaces) {
        const partial = workspace as Partial<IMpcWorkspace>;

        if (partial.members == null) {
            const owner = data.users.find(
                (item) => item.id === workspace.ownerId,
            );
            workspace.members = [
                {
                    userId: workspace.ownerId,
                    username: owner?.username ?? workspace.ownerId,
                    role: 'owner',
                    addedAt: workspace.createdAt,
                },
            ];
            changed = true;
        }
    }

    for (const system of data.systems) {
        if (system.workspaceId == null || system.workspaceId.length === 0) {
            system.workspaceId = ensureDefaultWorkspace(data, {
                id: system.createdBy,
            }).id;
            changed = true;
        }
    }

    return changed;
};

const GLOBAL_CACHE_KEY = '__mpcPocStore';

type GlobalWithStore = typeof globalThis & {
    [GLOBAL_CACHE_KEY]?: Record<string, IMpcStoreData>;
};

const getGlobalCache = (): Record<string, IMpcStoreData> => {
    const globalWithStore = globalThis as GlobalWithStore;
    globalWithStore[GLOBAL_CACHE_KEY] ??= {};

    return globalWithStore[GLOBAL_CACHE_KEY];
};

export const getDefaultMpcStorePath = (): string => {
    const envPath = process.env.MPC_POC_STORE_PATH?.trim();

    return envPath != null && envPath.length > 0
        ? envPath
        : join(process.cwd(), '.mpc-poc', 'store.json');
};

export class MpcStore {
    constructor(private readonly filePath: string) {}

    /**
     * Returns the in-memory data (loaded from disk on first access).
     */
    read = (): IMpcStoreData => {
        const cache = getGlobalCache();
        cache[this.filePath] ??= this.load();

        return this.upgrade(cache[this.filePath]);
    };

    /**
     * Applies a mutation to the data and persists it atomically. Returns the mutator result.
     */
    update = <TResult>(mutator: (data: IMpcStoreData) => TResult): TResult => {
        const data = this.read();
        const result = mutator(data);
        this.persist(data);

        return result;
    };

    /**
     * Drops the cached data (tests / tooling).
     */
    reset = (): void => {
        const cache = getGlobalCache();
        delete cache[this.filePath];
    };

    getFilePath = (): string => this.filePath;

    private load = (): IMpcStoreData => {
        if (!existsSync(this.filePath)) {
            return emptyStoreData();
        }

        const raw = readFileSync(this.filePath, 'utf8');
        const parsed = JSON.parse(raw) as Partial<IMpcStoreData>;
        const data: IMpcStoreData = {
            ...emptyStoreData(),
            ...parsed,
            version: 1,
        };

        if (migrateStoreData(data)) {
            this.persist(data);
        }

        return data;
    };

    /**
     * Data cached on globalThis may predate a schema change (Next.js HMR keeps the cache across module reloads):
     * fill the missing collections and migrate in place so a running dev server never sees a partial shape.
     */
    private upgrade = (data: IMpcStoreData): IMpcStoreData => {
        const partial = data as Partial<IMpcStoreData>;

        const needsUpgrade =
            partial.workspaces == null ||
            partial.workspacePolicies == null ||
            partial.workspaces.some(
                (item) => (item as Partial<IMpcWorkspace>).members == null,
            );

        if (needsUpgrade) {
            Object.assign(data, { ...emptyStoreData(), ...partial });
            migrateStoreData(data);
            this.persist(data);
        }

        return data;
    };

    private persist = (data: IMpcStoreData): void => {
        const directory = dirname(this.filePath);
        mkdirSync(directory, { recursive: true });

        const tmpPath = `${this.filePath}.${process.pid}.${Date.now()}.tmp`;
        writeFileSync(tmpPath, JSON.stringify(data, null, 2), {
            encoding: 'utf8',
            mode: 0o600,
        });
        renameSync(tmpPath, this.filePath);
    };
}

// Default store singleton (path resolved lazily from the environment).
let defaultStore: MpcStore | undefined;

export const getMpcStore = (): MpcStore => {
    defaultStore ??= new MpcStore(getDefaultMpcStorePath());

    return defaultStore;
};

export const nowIso = (): string => new Date().toISOString();
