#!/usr/bin/env bash
#
# Lido Money Machine demo — one-shot bootstrap.
#
# Idempotent: safe to re-run.  Assumes `docker compose up -d` has already
# brought up anvil + postgres + envio + hasura.  TLS/CORS/routing is owned
# by the host nginx (see ./nginx.lmm-demo.conf), not by this script.
#
# Steps:
#   1. Wait for anvil to be ready (eth_blockNumber).
#   2. If LMM DAO is already deployed (deployer balance dropped), skip.
#   3. Clone dao-launchpad@f/lido-demo if missing.
#   4. Run `just demo-up` against anvil (deploys CR slice + LMM + mocks + seed).
#   5. Write manifest.json into MANIFEST_OUTPUT_DIR (default /srv/lmm) so
#      nginx serves it as https://tests.aragon.in/manifest.json via the
#      `alias` directive in nginx.lmm-demo.conf.
#
# Usage:
#   MAINNET_RPC=... ./init-demo.sh
#   # optionally: MANIFEST_OUTPUT_DIR=/srv/lmm ./init-demo.sh

set -euo pipefail

DAO_LAUNCHPAD_DIR="${DAO_LAUNCHPAD_DIR:-/srv/dao-launchpad}"
DAO_LAUNCHPAD_REPO="${DAO_LAUNCHPAD_REPO:-https://github.com/aragon/dao-launchpad.git}"
DAO_LAUNCHPAD_BRANCH="${DAO_LAUNCHPAD_BRANCH:-f/lido-demo}"
ANVIL_RPC="${ANVIL_RPC:-http://127.0.0.1:8545}"
MANIFEST_OUTPUT_DIR="${MANIFEST_OUTPUT_DIR:-/srv/lmm}"
PUBLIC_HOSTNAME="${PUBLIC_HOSTNAME:-tests.aragon.in}"
COMPOSE_FILE="${COMPOSE_FILE:-$(dirname "$(readlink -f "$0")")/docker-compose.yml}"

log() { printf '\033[1;36m[init-demo]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[init-demo:ERROR]\033[0m %s\n' "$*" >&2; }

require_cmd() {
	if ! command -v "$1" &>/dev/null; then
		err "missing required command: $1"
		exit 1
	fi
}

require_cmd git
require_cmd jq
require_cmd cast
require_cmd just
require_cmd forge

log "waiting for anvil at $ANVIL_RPC..."
for i in $(seq 1 60); do
	if cast block-number --rpc-url "$ANVIL_RPC" &>/dev/null; then
		log "anvil ready"
		break
	fi
	sleep 2
	if [ "$i" -eq 60 ]; then
		err "anvil did not come up within 120s"
		exit 1
	fi
done

if [ ! -d "$DAO_LAUNCHPAD_DIR/.git" ]; then
	log "cloning $DAO_LAUNCHPAD_REPO @ $DAO_LAUNCHPAD_BRANCH → $DAO_LAUNCHPAD_DIR"
	git clone --branch "$DAO_LAUNCHPAD_BRANCH" --depth 1 --recurse-submodules \
		"$DAO_LAUNCHPAD_REPO" "$DAO_LAUNCHPAD_DIR"
else
	log "dao-launchpad already cloned; pulling latest"
	git -C "$DAO_LAUNCHPAD_DIR" fetch --depth 1 origin "$DAO_LAUNCHPAD_BRANCH"
	git -C "$DAO_LAUNCHPAD_DIR" reset --hard "origin/$DAO_LAUNCHPAD_BRANCH"
	git -C "$DAO_LAUNCHPAD_DIR" submodule update --init --recursive
fi

cd "$DAO_LAUNCHPAD_DIR/lido"

# `just switch mainnet` writes RPC_URL into .env — we don't need that since anvil is forked.
# But the foundry-tooling expects .env, so we synthesize one.
if [ ! -f .env ]; then
	log "creating minimal .env for lido package"
	cat >.env <<EOF
NETWORK_NAME=mainnet
CHAIN_ID=1
RPC_URL=$ANVIL_RPC
EOF
fi

# bootstrap pulls submodules (foundry libs); ignore if already bootstrapped.
just bootstrap || true

# Detect if demo-up already ran by reading the manifest's deployer balance — if
# anvil[0] is below its initial 10000 ETH, deployment has happened.  Cheap enough.
DEPLOYER_BAL=$(cast balance 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --rpc-url "$ANVIL_RPC" | head -c 6)
if [ -f script/demo/manifest.json ] && [ "${DEPLOYER_BAL%???}" -lt "10000" ]; then
	log "demo already deployed (deployer balance ${DEPLOYER_BAL}...); skipping demo-up"
else
	log "running just demo-up"
	just demo-up
fi

log "writing manifest into ${MANIFEST_OUTPUT_DIR}/manifest.json (host bind path served by nginx)"
mkdir -p "$MANIFEST_OUTPUT_DIR"
# Atomic replace — avoids serving a half-written file if nginx reads while
# init-demo.sh runs.
install -m 0644 script/demo/manifest.json "$MANIFEST_OUTPUT_DIR/manifest.json.tmp"
mv -f "$MANIFEST_OUTPUT_DIR/manifest.json.tmp" "$MANIFEST_OUTPUT_DIR/manifest.json"

# Pin Envio's mainnet start_block to the actual fork block (manifest's
# blockNumber minus a small buffer for off-by-one safety).  docker-compose
# reads this via env_file: /srv/lmm/.env.indexer.  Without this, a fresh
# `just demo-up` advances the fork block but the indexer keeps using the
# old start_block baked into config.yaml's default — which on first boot
# is fine, but on subsequent re-deploys means re-scanning known blocks.
FORK_BLOCK=$(jq -r '.blockNumber' script/demo/manifest.json)
INDEXER_START_BLOCK=$((FORK_BLOCK - 5))
log "pinning Envio start_block to ${INDEXER_START_BLOCK} (manifest fork block ${FORK_BLOCK} − 5)"
cat >"${MANIFEST_OUTPUT_DIR}/.env.indexer.tmp" <<EOF
# Auto-generated by init-demo.sh on $(date -u +%FT%TZ).
# Consumed by infra/lmm-demo/vm/docker-compose.yml → services.envio.env_file.
ENVIO_DEMO_START_BLOCK=${INDEXER_START_BLOCK}
EOF
mv -f "${MANIFEST_OUTPUT_DIR}/.env.indexer.tmp" "${MANIFEST_OUTPUT_DIR}/.env.indexer"

# Bounce envio so it picks up the new start_block.  Anvil + postgres + hasura
# stay up; only the indexer container is restarted.  envio's config-hash diff
# would have wiped the DB anyway on the next run because config.yaml's start
# block changed — but doing it explicitly keeps the log story clean.
if docker compose -f "$COMPOSE_FILE" ps --status running --services 2>/dev/null | grep -q '^envio$'; then
	log "restarting envio container to apply new start_block"
	docker compose -f "$COMPOSE_FILE" restart envio
fi

log "done.  LMM DAO: $(jq -r .lmm.dao script/demo/manifest.json)"
log "manifest served at: https://${PUBLIC_HOSTNAME}/manifest.json"
