export enum SettingsSlotId {
    SETTINGS_GOVERNANCE_SETTINGS_HOOK = 'SETTINGS_GOVERNANCE_SETTINGS_HOOK',
    SETTINGS_GOVERNANCE_SETTINGS_PARSE = 'SETTINGS_GOVERNANCE_SETTINGS_PARSE',
    SETTINGS_MEMBERS_INFO = 'SETTINGS_MEMBERS_INFO',
}
