export enum SettingsSlotId {
    SETTINGS_GOVERNANCE_SETTINGS_HOOK = 'SETTINGS_GOVERNANCE_SETTINGS_HOOK',
    SETTINGS_MEMBERS_INFO = 'SETTINGS_MEMBERS_INFO',
    SETTINGS_GOVERNANCE_INFO = 'SETTINGS_GOVERNANCE_INFO',
}
