export enum SettingsSlotId {
    SETTINGS_GOVERNANCE_SETTINGS_HOOK = 'SETTINGS_GOVERNANCE_SETTINGS_HOOK',
    SETTINGS_MEMBERS_INFO = 'SETTINGS_MEMBERS_INFO',
    SETTINGS_PANEL = 'SETTINGS_PANEL',
    SETTINGS_BUILD_PREPARE_PLUGIN_UPDATE_DATA = 'SETTINGS_BUILD_PREPARE_PLUGIN_UPDATE_DATA',
    SETTINGS_GET_UNINSTALL_HELPERS = 'SETTINGS_GET_UNINSTALL_HELPERS',
    SETTINGS_PLUGIN_TO_FORM_DATA = 'SETTINGS_PLUGIN_TO_FORM_DATA',
}
