export enum SettingsDialogId {
    UPDATE_DAO_CONTRACTS_LIST = 'UPDATE_DAO_CONTRACTS_LIST',
    PREPARE_DAO_CONTRACTS_UPDATE = 'PREPARE_DAO_CONTRACTS_UPDATE',
    GOVERNANCE_PROCESS_REQUIRED = 'GOVERNANCE_PROCESS_REQUIRED',
    UNINSTALL_PROCESS = 'UNINSTALL_PROCESS',
}
