export enum SettingsDialogId {
    UPDATE_DAO_CONTRACTS_LIST = 'UPDATE_DAO_CONTRACTS_LIST',
    PREPARE_DAO_CONTRACTS_UPDATE = 'PREPARE_DAO_CONTRACTS_UPDATE',
    GOVERNANCE_PROCESS_REQUIRED = 'GOVERNANCE_PROCESS_REQUIRED',
    UNINSTALL_PROCESS_ALERT = 'UNINSTALL_PROCESS_ALERT',
    PREPARE_PLUGIN_UNINSTALLATION = 'PREPARE_PLUGIN_UNINSTALLATION',
}
