export enum MpcDialogId {
    NEW_REQUEST = 'MPC_NEW_REQUEST',
    SIGN_REQUEST = 'MPC_SIGN_REQUEST',
    APPROVE_REQUEST = 'MPC_APPROVE_REQUEST',
    RESHARE = 'MPC_RESHARE',
    RECOVER = 'MPC_RECOVER',
    EXPORT_KEY = 'MPC_EXPORT_KEY',
    ADD_MEMBER = 'MPC_ADD_MEMBER',
    EDIT_POLICY = 'MPC_EDIT_POLICY',
    CREATE_WORKSPACE = 'MPC_CREATE_WORKSPACE',
    ADD_WORKSPACE_MEMBER = 'MPC_ADD_WORKSPACE_MEMBER',
}
