export const addressGaugeVoterAbi = [
    { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        name: 'GAUGE_ADMIN_ROLE',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'SET_TARGET_CONFIG_PERMISSION_ID',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'UPGRADE_PLUGIN_PERMISSION_ID',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'activateGauge',
        inputs: [{ name: '_gauge', type: 'address', internalType: 'address' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'clock',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'createGauge',
        inputs: [
            { name: '_gauge', type: 'address', internalType: 'address' },
            { name: '_metadataURI', type: 'string', internalType: 'string' },
        ],
        outputs: [{ name: 'gauge', type: 'address', internalType: 'address' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'currentEpochStart',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'dao',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'contract IDAO' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'deactivateGauge',
        inputs: [{ name: '_gauge', type: 'address', internalType: 'address' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'enableUpdateVotingPowerHook',
        inputs: [],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'epochGaugeVotes',
        inputs: [
            { name: '', type: 'uint256', internalType: 'uint256' },
            { name: '', type: 'address', internalType: 'address' },
        ],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'epochId',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'epochStart',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'epochTotalVotingPowerCast',
        inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'epochVoteEnd',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'epochVoteStart',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'escrow',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'gaugeExists',
        inputs: [{ name: '_gauge', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'gaugeList',
        inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'gaugeVotes',
        inputs: [
            { name: '_epoch', type: 'uint256', internalType: 'uint256' },
            { name: '_address', type: 'address', internalType: 'address' },
        ],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'gaugeVotes',
        inputs: [{ name: '_address', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'gauges',
        inputs: [{ name: '', type: 'address', internalType: 'address' }],
        outputs: [
            { name: 'active', type: 'bool', internalType: 'bool' },
            { name: 'created', type: 'uint256', internalType: 'uint256' },
            { name: 'metadataURI', type: 'string', internalType: 'string' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'gaugesVotedFor',
        inputs: [{ name: '_address', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getAllGauges',
        inputs: [],
        outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getCurrentTargetConfig',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'tuple',
                internalType: 'struct IPlugin.TargetConfig',
                components: [
                    { name: 'target', type: 'address', internalType: 'address' },
                    { name: 'operation', type: 'uint8', internalType: 'enum IPlugin.Operation' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getGauge',
        inputs: [{ name: '_gauge', type: 'address', internalType: 'address' }],
        outputs: [
            {
                name: '',
                type: 'tuple',
                internalType: 'struct IGauge.Gauge',
                components: [
                    { name: 'active', type: 'bool', internalType: 'bool' },
                    { name: 'created', type: 'uint256', internalType: 'uint256' },
                    { name: 'metadataURI', type: 'string', internalType: 'string' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getTargetConfig',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'tuple',
                internalType: 'struct IPlugin.TargetConfig',
                components: [
                    { name: 'target', type: 'address', internalType: 'address' },
                    { name: 'operation', type: 'uint8', internalType: 'enum IPlugin.Operation' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getWriteEpochId',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'implementation',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'initialize',
        inputs: [
            { name: '_dao', type: 'address', internalType: 'address' },
            { name: '_escrow', type: 'address', internalType: 'address' },
            { name: '_startPaused', type: 'bool', internalType: 'bool' },
            { name: '_clock', type: 'address', internalType: 'address' },
            { name: '_ivotesAdapter', type: 'address', internalType: 'address' },
            { name: '_enableUpdateVotingPowerHook', type: 'bool', internalType: 'bool' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'isActive',
        inputs: [{ name: '_gauge', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'isVoting',
        inputs: [{ name: '_address', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'ivotesAdapter',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    { type: 'function', name: 'pause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        name: 'paused',
        inputs: [],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'pluginType',
        inputs: [],
        outputs: [{ name: '', type: 'uint8', internalType: 'enum IPlugin.PluginType' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'protocolVersion',
        inputs: [],
        outputs: [{ name: '', type: 'uint8[3]', internalType: 'uint8[3]' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'proxiableUUID',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
        stateMutability: 'view',
    },
    { type: 'function', name: 'reset', inputs: [], outputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        name: 'setEnableUpdateVotingPowerHook',
        inputs: [{ name: '_enableUpdateVotingPowerHook', type: 'bool', internalType: 'bool' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'setIVotesAdapter',
        inputs: [{ name: '_ivotesAdapter', type: 'address', internalType: 'address' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'setTargetConfig',
        inputs: [
            {
                name: '_targetConfig',
                type: 'tuple',
                internalType: 'struct IPlugin.TargetConfig',
                components: [
                    { name: 'target', type: 'address', internalType: 'address' },
                    { name: 'operation', type: 'uint8', internalType: 'enum IPlugin.Operation' },
                ],
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'supportsInterface',
        inputs: [{ name: '_interfaceId', type: 'bytes4', internalType: 'bytes4' }],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'totalVotingPowerCast',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    { type: 'function', name: 'unpause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
    {
        type: 'function',
        name: 'updateGaugeMetadata',
        inputs: [
            { name: '_gauge', type: 'address', internalType: 'address' },
            { name: '_metadataURI', type: 'string', internalType: 'string' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'updateVotingPower',
        inputs: [
            { name: '_from', type: 'address', internalType: 'address' },
            { name: '_to', type: 'address', internalType: 'address' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'upgradeTo',
        inputs: [{ name: 'newImplementation', type: 'address', internalType: 'address' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'upgradeToAndCall',
        inputs: [
            { name: 'newImplementation', type: 'address', internalType: 'address' },
            { name: 'data', type: 'bytes', internalType: 'bytes' },
        ],
        outputs: [],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'usedVotingPower',
        inputs: [{ name: '_address', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'vote',
        inputs: [
            {
                name: '_votes',
                type: 'tuple[]',
                internalType: 'struct IAddressGaugeVote.GaugeVote[]',
                components: [
                    { name: 'weight', type: 'uint256', internalType: 'uint256' },
                    { name: 'gauge', type: 'address', internalType: 'address' },
                ],
            },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'votes',
        inputs: [
            { name: '_address', type: 'address', internalType: 'address' },
            { name: '_gauge', type: 'address', internalType: 'address' },
        ],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'votingActive',
        inputs: [],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'event',
        name: 'AdminChanged',
        inputs: [
            { name: 'previousAdmin', type: 'address', indexed: false, internalType: 'address' },
            { name: 'newAdmin', type: 'address', indexed: false, internalType: 'address' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'BeaconUpgraded',
        inputs: [{ name: 'beacon', type: 'address', indexed: true, internalType: 'address' }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'GaugeActivated',
        inputs: [{ name: 'gauge', type: 'address', indexed: true, internalType: 'address' }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'GaugeCreated',
        inputs: [
            { name: 'gauge', type: 'address', indexed: true, internalType: 'address' },
            { name: 'creator', type: 'address', indexed: true, internalType: 'address' },
            { name: 'metadataURI', type: 'string', indexed: false, internalType: 'string' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'GaugeDeactivated',
        inputs: [{ name: 'gauge', type: 'address', indexed: true, internalType: 'address' }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'GaugeMetadataUpdated',
        inputs: [
            { name: 'gauge', type: 'address', indexed: true, internalType: 'address' },
            { name: 'metadataURI', type: 'string', indexed: false, internalType: 'string' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Initialized',
        inputs: [{ name: 'version', type: 'uint8', indexed: false, internalType: 'uint8' }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Paused',
        inputs: [{ name: 'account', type: 'address', indexed: false, internalType: 'address' }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Reset',
        inputs: [
            { name: 'voter', type: 'address', indexed: true, internalType: 'address' },
            { name: 'gauge', type: 'address', indexed: true, internalType: 'address' },
            { name: 'epoch', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'votingPowerRemovedFromGauge', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'totalVotingPowerInGauge', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'totalVotingPowerInContract', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'TargetSet',
        inputs: [
            {
                name: 'newTargetConfig',
                type: 'tuple',
                indexed: false,
                internalType: 'struct IPlugin.TargetConfig',
                components: [
                    { name: 'target', type: 'address', internalType: 'address' },
                    { name: 'operation', type: 'uint8', internalType: 'enum IPlugin.Operation' },
                ],
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Unpaused',
        inputs: [{ name: 'account', type: 'address', indexed: false, internalType: 'address' }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Upgraded',
        inputs: [{ name: 'implementation', type: 'address', indexed: true, internalType: 'address' }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Voted',
        inputs: [
            { name: 'voter', type: 'address', indexed: true, internalType: 'address' },
            { name: 'gauge', type: 'address', indexed: true, internalType: 'address' },
            { name: 'epoch', type: 'uint256', indexed: true, internalType: 'uint256' },
            { name: 'votingPowerCastForGauge', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'totalVotingPowerInGauge', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'totalVotingPowerInContract', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
        ],
        anonymous: false,
    },
    { type: 'error', name: 'AlreadyInitialized', inputs: [] },
    { type: 'error', name: 'AlreadyVoted', inputs: [{ name: '_address', type: 'address', internalType: 'address' }] },
    {
        type: 'error',
        name: 'DaoUnauthorized',
        inputs: [
            { name: 'dao', type: 'address', internalType: 'address' },
            { name: 'where', type: 'address', internalType: 'address' },
            { name: 'who', type: 'address', internalType: 'address' },
            { name: 'permissionId', type: 'bytes32', internalType: 'bytes32' },
        ],
    },
    { type: 'error', name: 'DelegateCallFailed', inputs: [] },
    { type: 'error', name: 'DoubleVote', inputs: [] },
    { type: 'error', name: 'GaugeActivationUnchanged', inputs: [] },
    { type: 'error', name: 'GaugeDoesNotExist', inputs: [{ name: '_pool', type: 'address', internalType: 'address' }] },
    { type: 'error', name: 'GaugeExists', inputs: [] },
    { type: 'error', name: 'GaugeInactive', inputs: [{ name: '_gauge', type: 'address', internalType: 'address' }] },
    {
        type: 'error',
        name: 'InvalidTargetConfig',
        inputs: [
            {
                name: 'targetConfig',
                type: 'tuple',
                internalType: 'struct IPlugin.TargetConfig',
                components: [
                    { name: 'target', type: 'address', internalType: 'address' },
                    { name: 'operation', type: 'uint8', internalType: 'enum IPlugin.Operation' },
                ],
            },
        ],
    },
    { type: 'error', name: 'NoVotes', inputs: [] },
    { type: 'error', name: 'NoVotingPower', inputs: [] },
    { type: 'error', name: 'NotApprovedOrOwner', inputs: [] },
    { type: 'error', name: 'NotCurrentlyVoting', inputs: [] },
    { type: 'error', name: 'OnlyEscrow', inputs: [] },
    { type: 'error', name: 'UpdateVotingPowerHookNotEnabled', inputs: [] },
    { type: 'error', name: 'VotingInactive', inputs: [] },
    { type: 'error', name: 'ZeroGauge', inputs: [] },
] as const;
