export enum CreateDaoDialogId {
    PUBLISH_DAO = 'PUBLISH_DAO',
    CREATE_DAO_DETAILS = 'CREATE_DAO_DETAILS',
    CREATE_PROCESS_DETAILS = 'CREATE_PROCESS_DETAILS',
    PREPARE_PROCESS = 'PREPARE_PROCESS',
    SETUP_BODY = 'SETUP_BODY',
    SETUP_STAGE_TIMING = 'SETUP_STAGE_TIMING',
}
