export enum CreateDaoSlotId {
    CREATE_DAO_BUILD_PREPARE_PLUGIN_INSTALL_DATA = 'CREATE_DAO_BUILD_PREPARE_PLUGIN_INSTALL_DATA',
    CREATE_DAO_PROCESS_BODY_READ_FIELD = 'CREATE_DAO_PROCESS_BODY_READ_FIELD',
    CREATE_DAO_PROPOSAL_CREATION_SETTINGS = 'CREATE_DAO_PROPOSAL_CREATION_SETTINGS',
    CREATE_DAO_SETUP_MEMBERSHIP = 'CREATE_DAO_SETUP_MEMBERSHIP',
    CREATE_DAO_SETUP_GOVERNANCE = 'CREATE_DAO_SETUP_GOVERNANCE',
}
