export enum CreateDaoSlotId {
    CREATE_DAO_BUILD_PREPARE_PLUGIN_INSTALL_DATA = 'CREATE_DAO_BUILD_PREPARE_PLUGIN_INSTALL_DATA',
    CREATE_DAO_PROCESS_BODY_READ_FIELD = 'CREATE_DAO_PROCESS_BODY_READ_FIELD',
    CREATE_DAO_PROPOSAL_CREATION_REQUIREMENTS = 'CREATE_DAO_PROPOSAL_CREATION_REQUIREMENTS',
}
