import type { UseFormContextReturn } from '../../hooks';

export const generateFormContext = (context?: Partial<UseFormContextReturn>): UseFormContextReturn => ({
    watch: jest.fn(),
    getValues: jest.fn(),
    getFieldState: jest.fn(),
    setError: jest.fn(),
    clearErrors: jest.fn(),
    setValue: jest.fn(),
    trigger: jest.fn(),
    resetField: jest.fn(),
    reset: jest.fn(),
    handleSubmit: jest.fn(),
    unregister: jest.fn(),
    register: jest.fn(),
    setFocus: jest.fn(),
    control: {} as UseFormContextReturn['control'],
    subscribe: jest.fn(),
    formState: {
        isDirty: false,
        isLoading: false,
        isSubmitSuccessful: false,
        isSubmitted: false,
        isSubmitting: false,
        isValid: false,
        isValidating: false,
        isReady: false,
        disabled: false,
        submitCount: 0,
        dirtyFields: {},
        touchedFields: {},
        validatingFields: {},
        errors: {},
    },
    ...context,
});
