export enum LockToVotePluginDialogId {
    SUBMIT_VOTE_FEEDBACK = 'SUBMIT_VOTE_FEEDBACK',
    LOCK_BEFORE_VOTE = 'LOCK_BEFORE_VOTE',
    LOCK_UNLOCK_L2V = 'LOCK_UNLOCK_L2V',
    UNLOCK_BLOCKED_INFO = 'UNLOCK_BLOCKED_INFO',
    WITHDRAW_TRANSACTION = 'WITHDRAW_TRANSACTION',
}
