name: App E2E Dispatch

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      ## SET UP CREDENTIALS
      - name: Load secrets from OP
        id: op-load-secret
        uses: 1password/load-secrets-action@v2.0.0
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PRODUCTION_BACKUPS_TEMP }}
          GH_APP_QA: op://apikeys_production/gh-app-qa/credential

      - name: Trigger E2E Tests in App QA Repository
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ steps.op-load-secret.outputs.GH_APP_QA }}" \
            https://api.github.com/repos/aragon/app-qa/dispatches \
            -d '{"event_type": "E2E_Tests_App_Next_Dispatch"}'
